Repository apigee/apigee-devportal-kickstart-drupal, pull requests merged in 2021-04, with the labels that each got.

#463 Initial Commit for NGMint (ApigeeX 5G)
  themes/custom/apigee_kickstart/apigee_kickstart.libraries.yml
  themes/custom/apigee_kickstart/assets/css/apigee-kickstart.apigeex.css
  themes/custom/apigee_kickstart/assets/css/apigee-kickstart.style.css
  themes/custom/apigee_kickstart/includes/field.inc
  themes/custom/apigee_kickstart/src/sass/form/_form.user.scss
  themes/custom/apigee_kickstart/templates/apigee/apigee-entity--xrate-plan--full.html.twig
  themes/custom/apigee_kickstart/templates/apigee/apigee-entity--xrate-plan--teaser.html.twig
  themes/custom/apigee_kickstart/templates/page/page--xrate-plan.html.twig
Labels: cla: yes, enhancement

#464 Rate plan detail page UI changes (ApigeeX 5G)
  themes/custom/apigee_kickstart/assets/css/apigee-kickstart.style.css
  themes/custom/apigee_kickstart/templates/apigee/apigee-entity--xrate-plan--full.html.twig
Labels: cla: yes, enhancement

#467 New Feature Apigee X Monetization - NGMint
  themes/custom/apigee_kickstart/apigee_kickstart.libraries.yml
  themes/custom/apigee_kickstart/assets/css/apigee-kickstart.apigeex.css
  themes/custom/apigee_kickstart/assets/css/apigee-kickstart.style.css
  themes/custom/apigee_kickstart/includes/field.inc
  themes/custom/apigee_kickstart/src/sass/form/_form.user.scss
  themes/custom/apigee_kickstart/templates/apigee/apigee-entity--xrate-plan--full.html.twig
  themes/custom/apigee_kickstart/templates/apigee/apigee-entity--xrate-plan--teaser.html.twig
  themes/custom/apigee_kickstart/templates/page/page--xrate-plan.html.twig
Labels: cla: yes

#471 Call to a member function getValue() on null in ValidReferenceConstraintValidator class
  composer.json
Labels: bug, cla: yes
